// Sample screenplay for the trailer. Fiction written for this film: no real
// script, person or account appears here.
//
// `opening` is on the page when the script opens. The trailer types the
// lines in config.js EDITS after it. `rest` is everything the writer has
// "already written" by the time they export, so the PDF runs to three pages.
window.RT = window.RT || {};

RT.SCRIPT = {
  title: "LOW TIDE",
  author: "Nell Ashby",

  opening: [
    { type: "action", text: "FADE IN:" },
    { type: "scene", text: "INT. KEEPER'S COTTAGE - NIGHT" },
    { type: "action", text: "Rain hits the window in handfuls. A kettle ticks as it cools on the range." },
    { type: "action", text: "MARGOT (60s), oilskin still dripping, sorts fuses into a biscuit tin by candlelight." },
    { type: "action", text: "" },
  ],

  rest: [
    { type: "action", text: "She pockets it, then thumps the radio casing with the heel of her hand. It crackles back to life." },
    { type: "character", text: "TOM (V.O.)" },
    { type: "paren", text: "(through static)" },
    { type: "dialogue", text: "Harbour, this is Wren. Do you read?" },
    { type: "action", text: "Margot snatches up the handset." },
    { type: "character", text: "MARGOT" },
    { type: "dialogue", text: "Wren, Harbour. I read you. Where are you, Tom?" },
    { type: "character", text: "TOM (V.O.)" },
    { type: "dialogue", text: "Past the Sisters. Lost the light about ten minutes back." },
    { type: "action", text: "Margot looks to the window. The beam should be sweeping the bay. The glass is black." },
    { type: "character", text: "MARGOT" },
    { type: "dialogue", text: "Hold your heading. Give me two minutes." },
    { type: "action", text: "She drops the handset, takes a torch from the hook and shoulders the door open into the storm." },
    { type: "scene", text: "EXT. LIGHTHOUSE STAIR - CONTINUOUS" },
    { type: "action", text: "The wind takes the door out of her hand. She climbs, one fist on the rail, the torch beam jumping across wet stone." },
    { type: "action", text: "Halfway up, the torch dies too." },
    { type: "action", text: "She keeps climbing in the dark, counting under her breath." },
    { type: "character", text: "MARGOT" },
    { type: "paren", text: "(counting)" },
    { type: "dialogue", text: "Sixty-one. Sixty-two. Sixty-three." },
    { type: "scene", text: "INT. LAMP ROOM - CONTINUOUS" },
    { type: "action", text: "The great lens sits dark and still. Margot feels along the wall for the breaker, finds it, pulls." },
    { type: "action", text: "Nothing." },
    { type: "action", text: "She opens the panel. One fuse inside, blackened through. She takes the last one from her pocket and twists it home." },
    { type: "action", text: "She pulls the breaker again." },
    { type: "action", text: "The lens shudders, then turns. Light fills the room and swings out over the water." },
    { type: "character", text: "MARGOT" },
    { type: "dialogue", text: "There you are." },
    { type: "scene", text: "EXT. BAY - CONTINUOUS" },
    { type: "action", text: "Far out, a small boat leans into the swell and turns toward the beam." },
    { type: "scene", text: "EXT. HARBOUR WALL - NIGHT" },
    { type: "action", text: "The Wren noses in under the light, deck awash. TOM (30s) throws a line at the bollard and misses. He throws again. It holds." },
    { type: "action", text: "He sits down hard on the wet deck and laughs at nothing." },
    { type: "character", text: "TOM" },
    { type: "paren", text: "(into the handset)" },
    { type: "dialogue", text: "Harbour, Wren. I'm in. Put the kettle on." },
    { type: "character", text: "MARGOT (V.O.)" },
    { type: "dialogue", text: "It's been on since nine." },
    { type: "scene", text: "INT. KEEPER'S COTTAGE - LATER" },
    { type: "action", text: "The kettle is singing. Margot sits at the table in her wet coat, the empty biscuit tin open in front of her." },
    { type: "action", text: "Boots on the step. The door opens. Tom stands there, soaked to the skin, grinning." },
    { type: "character", text: "TOM" },
    { type: "dialogue", text: "You took your time." },
    { type: "character", text: "MARGOT" },
    { type: "dialogue", text: "Shut the door. You're letting the weather in." },
    { type: "action", text: "He shuts it and drips on the mat. She pours two cups." },
    { type: "character", text: "TOM" },
    { type: "dialogue", text: "The light went out." },
    { type: "character", text: "MARGOT" },
    { type: "dialogue", text: "I noticed." },
    { type: "character", text: "TOM" },
    { type: "dialogue", text: "You climbed it in the dark?" },
    { type: "character", text: "MARGOT" },
    { type: "dialogue", text: "Sixty-three steps. I've had thirty years to learn them." },
    { type: "action", text: "She slides a cup across the table. He wraps both hands round it." },
    { type: "transition", text: "FADE OUT." },
  ],
};
